master:
  image: gcr.io/google_containers/hyperkube:1.3.0
  net: host
  pid: host
  privileged: true
  restart: always
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:rw
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
    - /srv/kubernetes:/srv/kubernetes
  command: |
    /hyperkube kubelet
    --address="0.0.0.0"
    --allow-privileged=true
    --api-servers=http://localhost:8080
    --cluster-dns={{ pillar['dns_server'] }}
    --cluster-domain={{ pillar['dns_domain'] }}
    --config=/etc/kubernetes/manifests
    --containerized
    --hostname-override="{{ private_address }}"
    --tls-cert-file="/srv/kubernetes/server.crt"
    --tls-private-key-file="/srv/kubernetes/server.key"
    --v=2
