version: '2'

networks:
  internal:
    driver: bridge

services:
  etcd:
    image: gcr.io/google_containers/etcd:2.2.1
    command: ['/usr/local/bin/etcd', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data']
    ports:
     - "4001:4001"
    networks:
     internal:
       aliases:
        - etcd-alias

  apiserver:
    image: gcr.io/google_containers/hyperkube:v1.0.1
    command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--address=0.0.0.0", "--etcd_servers=http://etcd-alias:4001", "--cluster_name=kubernetes", "--v=2"]
    ports:
     - "8080:8080"
    networks:
     internal:
       aliases:
        - apiserver-alias

  controller:
    image:  gcr.io/google_containers/hyperkube:v1.0.1
    command: ["/hyperkube", "controller-manager", "--master=http://apiserver-alias:8080", "--v=2"]
    networks:
     internal:
       aliases:
        - controller-alias

  scheduler:
    image:  gcr.io/google_containers/hyperkube:v1.0.1
    command: ["/hyperkube", "scheduler", "--master=http://apiserver-alias:8080", "--v=2"]
    networks:
     internal:
       aliases:
        - scheduler-alias

  kubelet:
    image:  gcr.io/google_containers/hyperkube:v1.0.1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    command: ['/hyperkube', 'kubelet', '--api_servers=http://apiserver-alias:8080', '--v=2', '--address=0.0.0.0', '--enable_server']
    networks:
     internal:
       aliases:
        - kubelet-alias

  proxy:
    image:  gcr.io/google_containers/hyperkube:v1.0.1
    privileged: true
    command: ['/hyperkube', 'proxy', '--master=http://apiserver-alias:8080', '--v=2']
    networks:
     internal:
       aliases:
        - proxy-alias